stages:
  data_ingestion:
    cmd: python src/data_inestion.py
    deps:
    - src/data/data_inestion.py
    params:
    - params.yaml
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    outs:
    - data/processed
